### PR TITLE
Allow STS session-style authentication using a SESSION_KEY variable

### PR DESCRIPTION
**Pull request by nkrumm**
Hi,

This is a pre-req for the PR I am about to submit for the main nextflow repo (https://github.com/nextflow-io/nextflow/pull/1248) to address https://github.com/nextflow-io/nextflow/issues/934 there. 

I'm going to need some help finishing this-- I have virtually no experience with Java/groovy and so this was a bit of poking around in the dark. I *think* this compiles, but I have no way to really check if it works. I'll expand more in the PR in the other repo, but I am also not sure I can get the nextflow gradle config to use the local (modified) version of nextflow-s3fs.

### CODE REVIEW

**Comment by pditommaso** [comment]
Hi, thanks for this PR. Unfortunately, tests for this library are in complete disarray since this library was forked from another project. 

Currently, I'm just compiling and testing it from the nextflow project.

Just one thing, I would suggest renaming `sessionKey` to `sessionToken` to avoid naming overlapping with the other keys attribute.

**Comment by nkrumm** [comment]
> Just one thing, I would suggest renaming sessionKey to sessionToken to avoid naming overlapping with the other keys attribute.


Done. 

> Currently, I'm just compiling and testing it from the nextflow project.

This is where I need some help-- I would love to test this with nextflow but not sure how to go about this.

**Comment by pditommaso** [comment]
I've merged this manually, simplifying a bit the code. Could you review it and close this it's fine? 

eb3b57500f3cfac7ad1b3364e02ca4bb3250b6e9

**Comment by nkrumm** [comment]
Thanks for merging. Code looks OK to me, but when I try to build (`make compile`) I'm not sure I'm getting the updated nextflow-s3fs package and I get the following error:

```
Aug-24 15:34:05.179 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.UnsupportedOperationException: null
	at java.util.Collections$UnmodifiableMap.put(Collections.java:1457)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.get(DefaultGroovyMethods.java:7788)
	at org.codehaus.groovy.runtime.dgm$288.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
	at nextflow.Global.getAwsCredentials0(Global.groovy:105)
```
Is that because I'm not including the `io.nextflow:nxf-s3fs:1.0.7-SNAPSHOT` correctly?

**Comment by pditommaso** [comment]
Resync your branch with the latest changes on master. That should fix.

**Comment by kolarji2** [comment]
Hi, what is the status of the nextflow support for AWS_SESSION_TOKEN?

**Comment by pditommaso** [comment]
As commented [here](https://github.com/nextflow-io/nextflow/issues/1724#issuecomment-1367056346) this change implemented a partial solution. 

Note also this project has been merged in the [core](https://github.com/nextflow-io/nextflow) project.

**Pull request closed without merging**
