### PR TITLE
Enable KMS Support

### PR DESCRIPTION
**Pull request by mageshwarm**

### CODE REVIEW

**Comment by abhi18av** [comment]
CC @pditommaso

**Comment by abhi18av** [comment]
Hi @mageshwarm , 

Could you please sign the DCO for this contribution?

**Comment by pditommaso** [comment]
Hello  @mageshwarm, we need the commit signed to move on with this PR. Thanks!

**Comment by pditommaso** [comment]
This has been implemented in the main nextflow repo https://github.com/nextflow-io/nextflow/commit/c1e45aa98128e5c83968b2c129b85596b1b2eaec

**Pull request closed without merging**
